<?php

echo "<h1>UserController</h1>";

echo $this->tag->linkTo(["users/new", "create User", 'class' => 'btn btn-primary']);

    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>last Name</th>
            <th>Email</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Users quantity: <?php  ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($page->items as $user) { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->name; ?></td>
                <td><?php echo $user->last_name; ?></td>
                <td><?php echo $user->email; ?></td>

                <td><?php echo $this->tag->linkTo(["users/edit/" . $user->id, "Edit",'class' => 'btn btn-success']); ?></td>
                <td><?php echo $this->tag->linkTo(["users/delete/" . $user->id, "Delete",'class' => 'btn btn-danger']); ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php

?>

<a href="/index">First</a>
<a href="/index?page=<?= $page->before; ?>">Previous</a>
<a href="/index?page=<?= $page->next; ?>">Next</a>
<a href="/index?page=<?= $page->last; ?>">Last</a>

