<h2>Edit User</h2>

<?php echo $this->tag->form("users/update"); ?>

<p>
    <label for="name">Name</label>
    <?php echo $this->tag->textField("name"); ?>
</p>

<p>
    <label for="name">last Name</label>
    <?php echo $this->tag->textField("lastName"); ?>
</p>


<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField("email"); ?>
</p>

<?php echo $this->tag->hiddenField("id") ?>


<p>
    <?php echo $this->tag->submitButton("save"); ?>
</p>

</form>

