<h2>Create User</h2>

<?php echo $this->tag->form("users/create"); ?>

<p>
    <label for="name">Name</label>
    <?php echo $this->tag->textField("name"); ?>
</p>

<p>
    <label for="name">Last Name</label>
    <?php echo $this->tag->textField("lastName"); ?>
</p>

<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField("email"); ?>
</p>

<p>
    <?php echo $this->tag->submitButton("save"); ?>
</p>

</form>
